const BUILTIN = [
  {name:{common:"Afghanistan"},cca3:"AFG",flags:{svg:"https://flagcdn.com/af.svg"},capital:["Kabul"],population:40218234,region:"Asia",subregion:"Southern Asia",languages:{prs:"Dari",pus:"Pashto"},currencies:{AFN:{name:"Afghan afghani",symbol:"؋"}},timezones:["UTC+04:30"],borders:["IRN","PAK","TKM","UZB","TJK","CHN"],area:652230},
  {name:{common:"Albania"},cca3:"ALB",flags:{svg:"https://flagcdn.com/al.svg"},capital:["Tirana"],population:2837743,region:"Europe",subregion:"Southeast Europe",languages:{sqi:"Albanian"},currencies:{ALL:{name:"Albanian lek",symbol:"L"}},timezones:["UTC+01:00"],borders:["MNE","GRC","MKD","SRB"],area:28748},
  {name:{common:"Algeria"},cca3:"DZA",flags:{svg:"https://flagcdn.com/dz.svg"},capital:["Algiers"],population:44700000,region:"Africa",subregion:"Northern Africa",languages:{ara:"Arabic"},currencies:{DZD:{name:"Algerian dinar",symbol:"د.ج"}},timezones:["UTC+01:00"],borders:["TUN","LBY","NER","ESH","MRT","MLI","MAR"],area:2381741},
  {name:{common:"Argentina"},cca3:"ARG",flags:{svg:"https://flagcdn.com/ar.svg"},capital:["Buenos Aires"],population:45376763,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{ARS:{name:"Argentine peso",symbol:"$"}},timezones:["UTC-03:00"],borders:["BOL","BRA","CHL","PRY","URY"],area:2780400},
  {name:{common:"Australia"},cca3:"AUS",flags:{svg:"https://flagcdn.com/au.svg"},capital:["Canberra"],population:25687041,region:"Oceania",subregion:"Australia and New Zealand",languages:{eng:"English"},currencies:{AUD:{name:"Australian dollar",symbol:"$"}},timezones:["UTC+05:00","UTC+06:30","UTC+07:00","UTC+08:00","UTC+09:30","UTC+10:00","UTC+10:30","UTC+11:30"],borders:[],area:7692024},
  {name:{common:"Austria"},cca3:"AUT",flags:{svg:"https://flagcdn.com/at.svg"},capital:["Vienna"],population:9006400,region:"Europe",subregion:"Central Europe",languages:{deu:"German"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+01:00"],borders:["CZE","DEU","HUN","ITA","LIE","SVK","SVN","CHE"],area:83871},
  {name:{common:"Bangladesh"},cca3:"BGD",flags:{svg:"https://flagcdn.com/bd.svg"},capital:["Dhaka"],population:164689383,region:"Asia",subregion:"Southern Asia",languages:{ben:"Bengali"},currencies:{BDT:{name:"Bangladeshi taka",symbol:"৳"}},timezones:["UTC+06:00"],borders:["MMR","IND"],area:147570},
  {name:{common:"Belgium"},cca3:"BEL",flags:{svg:"https://flagcdn.com/be.svg"},capital:["Brussels"],population:11555997,region:"Europe",subregion:"Western Europe",languages:{deu:"German",fra:"French",nld:"Dutch"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+01:00"],borders:["FRA","DEU","LUX","NLD"],area:30528},
  {name:{common:"Bolivia"},cca3:"BOL",flags:{svg:"https://flagcdn.com/bo.svg"},capital:["Sucre"],population:11673029,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{BOB:{name:"Bolivian boliviano",symbol:"Bs."}},timezones:["UTC-04:00"],borders:["ARG","BRA","CHL","PRY","PER"],area:1098581},
  {name:{common:"Brazil"},cca3:"BRA",flags:{svg:"https://flagcdn.com/br.svg"},capital:["Brasília"],population:214326223,region:"Americas",subregion:"South America",languages:{por:"Portuguese"},currencies:{BRL:{name:"Brazilian real",symbol:"R$"}},timezones:["UTC-05:00","UTC-04:00","UTC-03:00","UTC-02:00"],borders:["ARG","BOL","COL","GUF","GUY","PRY","PER","SUR","URY","VEN"],area:8515767},
  {name:{common:"Canada"},cca3:"CAN",flags:{svg:"https://flagcdn.com/ca.svg"},capital:["Ottawa"],population:38005238,region:"Americas",subregion:"North America",languages:{eng:"English",fra:"French"},currencies:{CAD:{name:"Canadian dollar",symbol:"$"}},timezones:["UTC-08:00","UTC-07:00","UTC-06:00","UTC-05:00","UTC-04:00","UTC-03:30"],borders:["USA"],area:9984670},
  {name:{common:"Chile"},cca3:"CHL",flags:{svg:"https://flagcdn.com/cl.svg"},capital:["Santiago"],population:19116201,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{CLP:{name:"Chilean peso",symbol:"$"}},timezones:["UTC-06:00","UTC-04:00"],borders:["ARG","BOL","PER"],area:756102},
  {name:{common:"China"},cca3:"CHN",flags:{svg:"https://flagcdn.com/cn.svg"},capital:["Beijing"],population:1402112000,region:"Asia",subregion:"Eastern Asia",languages:{zho:"Chinese"},currencies:{CNY:{name:"Chinese yuan",symbol:"¥"}},timezones:["UTC+08:00"],borders:["AFG","BTN","MMR","HKG","IND","KAZ","PRK","KGZ","LAO","MAC","MNG","PAK","RUS","TJK","VNM"],area:9706961},
  {name:{common:"Colombia"},cca3:"COL",flags:{svg:"https://flagcdn.com/co.svg"},capital:["Bogotá"],population:50882891,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{COP:{name:"Colombian peso",symbol:"$"}},timezones:["UTC-05:00"],borders:["BRA","ECU","PAN","PER","VEN"],area:1141748},
  {name:{common:"Croatia"},cca3:"HRV",flags:{svg:"https://flagcdn.com/hr.svg"},capital:["Zagreb"],population:3899133,region:"Europe",subregion:"Southeast Europe",languages:{hrv:"Croatian"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+01:00"],borders:["BIH","HUN","MNE","SRB","SVN"],area:56594},
  {name:{common:"Czech Republic"},cca3:"CZE",flags:{svg:"https://flagcdn.com/cz.svg"},capital:["Prague"],population:10900555,region:"Europe",subregion:"Central Europe",languages:{ces:"Czech"},currencies:{CZK:{name:"Czech koruna",symbol:"Kč"}},timezones:["UTC+01:00"],borders:["AUT","DEU","POL","SVK"],area:78866},
  {name:{common:"Denmark"},cca3:"DNK",flags:{svg:"https://flagcdn.com/dk.svg"},capital:["Copenhagen"],population:5831404,region:"Europe",subregion:"Northern Europe",languages:{dan:"Danish"},currencies:{DKK:{name:"Danish krone",symbol:"kr"}},timezones:["UTC-04:00","UTC-03:00","UTC-01:00","UTC","UTC+01:00"],borders:["DEU"],area:43094},
  {name:{common:"Ecuador"},cca3:"ECU",flags:{svg:"https://flagcdn.com/ec.svg"},capital:["Quito"],population:17643060,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{USD:{name:"United States dollar",symbol:"$"}},timezones:["UTC-06:00","UTC-05:00"],borders:["COL","PER"],area:283561},
  {name:{common:"Egypt"},cca3:"EGY",flags:{svg:"https://flagcdn.com/eg.svg"},capital:["Cairo"],population:102334403,region:"Africa",subregion:"Northern Africa",languages:{ara:"Arabic"},currencies:{EGP:{name:"Egyptian pound",symbol:"£"}},timezones:["UTC+02:00"],borders:["ISR","LBY","SDN"],area:1002450},
  {name:{common:"Ethiopia"},cca3:"ETH",flags:{svg:"https://flagcdn.com/et.svg"},capital:["Addis Ababa"],population:114963583,region:"Africa",subregion:"Eastern Africa",languages:{amh:"Amharic"},currencies:{ETB:{name:"Ethiopian birr",symbol:"Br"}},timezones:["UTC+03:00"],borders:["DJI","ERI","KEN","SOM","SSD","SDN"],area:1104300},
  {name:{common:"Finland"},cca3:"FIN",flags:{svg:"https://flagcdn.com/fi.svg"},capital:["Helsinki"],population:5530719,region:"Europe",subregion:"Northern Europe",languages:{fin:"Finnish",swe:"Swedish"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+02:00"],borders:["NOR","RUS","SWE"],area:338424},
  {name:{common:"France"},cca3:"FRA",flags:{svg:"https://flagcdn.com/fr.svg"},capital:["Paris"],population:67391582,region:"Europe",subregion:"Western Europe",languages:{fra:"French"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC-10:00","UTC-09:30","UTC-09:00","UTC-08:00","UTC-04:00","UTC-03:00","UTC+01:00","UTC+02:00","UTC+03:00","UTC+04:00","UTC+05:00","UTC+11:00","UTC+12:00"],borders:["AND","BEL","DEU","ITA","LUX","MCO","ESP","CHE"],area:551695},
  {name:{common:"Germany"},cca3:"DEU",flags:{svg:"https://flagcdn.com/de.svg"},capital:["Berlin"],population:83240525,region:"Europe",subregion:"Western Europe",languages:{deu:"German"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+01:00"],borders:["AUT","BEL","CZE","DNK","FRA","LUX","NLD","POL","CHE"],area:357114},
  {name:{common:"Ghana"},cca3:"GHA",flags:{svg:"https://flagcdn.com/gh.svg"},capital:["Accra"],population:31072945,region:"Africa",subregion:"Western Africa",languages:{eng:"English"},currencies:{GHS:{name:"Ghanaian cedi",symbol:"₵"}},timezones:["UTC"],borders:["BFA","CIV","TGO"],area:238533},
  {name:{common:"Greece"},cca3:"GRC",flags:{svg:"https://flagcdn.com/gr.svg"},capital:["Athens"],population:10715549,region:"Europe",subregion:"Southern Europe",languages:{ell:"Greek"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+02:00"],borders:["ALB","BGR","TUR","MKD"],area:131990},
  {name:{common:"Guatemala"},cca3:"GTM",flags:{svg:"https://flagcdn.com/gt.svg"},capital:["Guatemala City"],population:16858333,region:"Americas",subregion:"Central America",languages:{spa:"Spanish"},currencies:{GTQ:{name:"Guatemalan quetzal",symbol:"Q"}},timezones:["UTC-06:00"],borders:["BLZ","HND","MEX","SLV"],area:108889},
  {name:{common:"Hungary"},cca3:"HUN",flags:{svg:"https://flagcdn.com/hu.svg"},capital:["Budapest"],population:9749763,region:"Europe",subregion:"Central Europe",languages:{hun:"Hungarian"},currencies:{HUF:{name:"Hungarian forint",symbol:"Ft"}},timezones:["UTC+01:00"],borders:["AUT","HRV","ROU","SRB","SVK","SVN","UKR"],area:93028},
  {name:{common:"Iceland"},cca3:"ISL",flags:{svg:"https://flagcdn.com/is.svg"},capital:["Reykjavík"],population:366425,region:"Europe",subregion:"Northern Europe",languages:{isl:"Icelandic"},currencies:{ISK:{name:"Icelandic króna",symbol:"kr"}},timezones:["UTC"],borders:[],area:103000},
  {name:{common:"India"},cca3:"IND",flags:{svg:"https://flagcdn.com/in.svg"},capital:["New Delhi"],population:1380004385,region:"Asia",subregion:"Southern Asia",languages:{eng:"English",hin:"Hindi"},currencies:{INR:{name:"Indian rupee",symbol:"₹"}},timezones:["UTC+05:30"],borders:["BGD","BTN","CHN","MMR","NPL","PAK"],area:3287590},
  {name:{common:"Indonesia"},cca3:"IDN",flags:{svg:"https://flagcdn.com/id.svg"},capital:["Jakarta"],population:273523621,region:"Asia",subregion:"South-Eastern Asia",languages:{ind:"Indonesian"},currencies:{IDR:{name:"Indonesian rupiah",symbol:"Rp"}},timezones:["UTC+07:00","UTC+08:00","UTC+09:00"],borders:["TLS","MYS","PNG"],area:1904569},
  {name:{common:"Iran"},cca3:"IRN",flags:{svg:"https://flagcdn.com/ir.svg"},capital:["Tehran"],population:83992953,region:"Asia",subregion:"Southern Asia",languages:{fas:"Persian"},currencies:{IRR:{name:"Iranian rial",symbol:"﷼"}},timezones:["UTC+03:30"],borders:["AFG","ARM","AZE","IRQ","PAK","TUR","TKM"],area:1648195},
  {name:{common:"Iraq"},cca3:"IRQ",flags:{svg:"https://flagcdn.com/iq.svg"},capital:["Baghdad"],population:40222503,region:"Asia",subregion:"Western Asia",languages:{ara:"Arabic",arc:"Aramaic",ckb:"Sorani Kurdish"},currencies:{IQD:{name:"Iraqi dinar",symbol:"ع.د"}},timezones:["UTC+03:00"],borders:["IRN","JOR","KWT","SAU","SYR","TUR"],area:438317},
  {name:{common:"Ireland"},cca3:"IRL",flags:{svg:"https://flagcdn.com/ie.svg"},capital:["Dublin"],population:4994724,region:"Europe",subregion:"Northern Europe",languages:{eng:"English",gle:"Irish"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC"],borders:["GBR"],area:70273},
  {name:{common:"Israel"},cca3:"ISR",flags:{svg:"https://flagcdn.com/il.svg"},capital:["Jerusalem"],population:9216900,region:"Asia",subregion:"Western Asia",languages:{ara:"Arabic",heb:"Hebrew"},currencies:{ILS:{name:"Israeli new shekel",symbol:"₪"}},timezones:["UTC+02:00"],borders:["EGY","JOR","LBN","SYR"],area:20770},
  {name:{common:"Italy"},cca3:"ITA",flags:{svg:"https://flagcdn.com/it.svg"},capital:["Rome"],population:59554023,region:"Europe",subregion:"Southern Europe",languages:{ita:"Italian"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC+01:00"],borders:["AUT","FRA","SMR","SVN","CHE","VAT"],area:301336},
  {name:{common:"Jamaica"},cca3:"JAM",flags:{svg:"https://flagcdn.com/jm.svg"},capital:["Kingston"],population:2961161,region:"Americas",subregion:"Caribbean",languages:{eng:"English"},currencies:{JMD:{name:"Jamaican dollar",symbol:"$"}},timezones:["UTC-05:00"],borders:[],area:10991},
  {name:{common:"Japan"},cca3:"JPN",flags:{svg:"https://flagcdn.com/jp.svg"},capital:["Tokyo"],population:125836021,region:"Asia",subregion:"Eastern Asia",languages:{jpn:"Japanese"},currencies:{JPY:{name:"Japanese yen",symbol:"¥"}},timezones:["UTC+09:00"],borders:[],area:377930},
  {name:{common:"Jordan"},cca3:"JOR",flags:{svg:"https://flagcdn.com/jo.svg"},capital:["Amman"],population:10203140,region:"Asia",subregion:"Western Asia",languages:{ara:"Arabic"},currencies:{JOD:{name:"Jordanian dinar",symbol:"د.ا"}},timezones:["UTC+03:00"],borders:["IRQ","ISR","SAU","SYR"],area:89342},
  {name:{common:"Kenya"},cca3:"KEN",flags:{svg:"https://flagcdn.com/ke.svg"},capital:["Nairobi"],population:53771300,region:"Africa",subregion:"Eastern Africa",languages:{eng:"English",swa:"Swahili"},currencies:{KES:{name:"Kenyan shilling",symbol:"Ksh"}},timezones:["UTC+03:00"],borders:["ETH","SOM","SSD","TZA","UGA"],area:580367},
  {name:{common:"Malaysia"},cca3:"MYS",flags:{svg:"https://flagcdn.com/my.svg"},capital:["Kuala Lumpur"],population:32365998,region:"Asia",subregion:"South-Eastern Asia",languages:{msa:"Malay"},currencies:{MYR:{name:"Malaysian ringgit",symbol:"RM"}},timezones:["UTC+08:00"],borders:["BRN","IDN","THA"],area:329613},
  {name:{common:"Mexico"},cca3:"MEX",flags:{svg:"https://flagcdn.com/mx.svg"},capital:["Mexico City"],population:128932753,region:"Americas",subregion:"North America",languages:{spa:"Spanish"},currencies:{MXN:{name:"Mexican peso",symbol:"$"}},timezones:["UTC-08:00","UTC-07:00","UTC-06:00"],borders:["BLZ","GTM","USA"],area:1964375},
  {name:{common:"Morocco"},cca3:"MAR",flags:{svg:"https://flagcdn.com/ma.svg"},capital:["Rabat"],population:36910558,region:"Africa",subregion:"Northern Africa",languages:{ara:"Arabic",ber:"Berber"},currencies:{MAD:{name:"Moroccan dirham",symbol:"د.م."}},timezones:["UTC+01:00"],borders:["DZA","ESH","ESP"],area:446550},
  {name:{common:"Nepal"},cca3:"NPL",flags:{svg:"https://flagcdn.com/np.svg"},capital:["Kathmandu"],population:29136808,region:"Asia",subregion:"Southern Asia",languages:{nep:"Nepali"},currencies:{NPR:{name:"Nepalese rupee",symbol:"₨"}},timezones:["UTC+05:45"],borders:["CHN","IND"],area:147181},
  {name:{common:"Netherlands"},cca3:"NLD",flags:{svg:"https://flagcdn.com/nl.svg"},capital:["Amsterdam"],population:17441139,region:"Europe",subregion:"Western Europe",languages:{nld:"Dutch"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC-04:00","UTC+01:00"],borders:["BEL","DEU"],area:41850},
  {name:{common:"New Zealand"},cca3:"NZL",flags:{svg:"https://flagcdn.com/nz.svg"},capital:["Wellington"],population:5084300,region:"Oceania",subregion:"Australia and New Zealand",languages:{eng:"English",mri:"Māori"},currencies:{NZD:{name:"New Zealand dollar",symbol:"$"}},timezones:["UTC-11:00","UTC-10:00","UTC+12:00","UTC+12:45","UTC+13:00"],borders:[],area:270467},
  {name:{common:"Nigeria"},cca3:"NGA",flags:{svg:"https://flagcdn.com/ng.svg"},capital:["Abuja"],population:206139587,region:"Africa",subregion:"Western Africa",languages:{eng:"English"},currencies:{NGN:{name:"Nigerian naira",symbol:"₦"}},timezones:["UTC+01:00"],borders:["BEN","CMR","TCD","NER"],area:923768},
  {name:{common:"Norway"},cca3:"NOR",flags:{svg:"https://flagcdn.com/no.svg"},capital:["Oslo"],population:5379475,region:"Europe",subregion:"Northern Europe",languages:{nor:"Norwegian"},currencies:{NOK:{name:"Norwegian krone",symbol:"kr"}},timezones:["UTC+01:00"],borders:["FIN","RUS","SWE"],area:323802},
  {name:{common:"Pakistan"},cca3:"PAK",flags:{svg:"https://flagcdn.com/pk.svg"},capital:["Islamabad"],population:220892331,region:"Asia",subregion:"Southern Asia",languages:{eng:"English",urd:"Urdu"},currencies:{PKR:{name:"Pakistani rupee",symbol:"₨"}},timezones:["UTC+05:00"],borders:["AFG","CHN","IND","IRN"],area:881912},
  {name:{common:"Peru"},cca3:"PER",flags:{svg:"https://flagcdn.com/pe.svg"},capital:["Lima"],population:32971846,region:"Americas",subregion:"South America",languages:{aym:"Aymara",que:"Quechua",spa:"Spanish"},currencies:{PEN:{name:"Peruvian sol",symbol:"S/."}},timezones:["UTC-05:00"],borders:["BOL","BRA","CHL","COL","ECU"],area:1285216},
  {name:{common:"Philippines"},cca3:"PHL",flags:{svg:"https://flagcdn.com/ph.svg"},capital:["Manila"],population:109581085,region:"Asia",subregion:"South-Eastern Asia",languages:{eng:"English",fil:"Filipino"},currencies:{PHP:{name:"Philippine peso",symbol:"₱"}},timezones:["UTC+08:00"],borders:[],area:342353},
  {name:{common:"Poland"},cca3:"POL",flags:{svg:"https://flagcdn.com/pl.svg"},capital:["Warsaw"],population:37950802,region:"Europe",subregion:"Central Europe",languages:{pol:"Polish"},currencies:{PLN:{name:"Polish złoty",symbol:"zł"}},timezones:["UTC+01:00"],borders:["BLR","CZE","DEU","LTU","RUS","SVK","UKR"],area:312679},
  {name:{common:"Portugal"},cca3:"PRT",flags:{svg:"https://flagcdn.com/pt.svg"},capital:["Lisbon"],population:10305564,region:"Europe",subregion:"Southern Europe",languages:{por:"Portuguese"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC-01:00","UTC"],borders:["ESP"],area:92212},
  {name:{common:"Romania"},cca3:"ROU",flags:{svg:"https://flagcdn.com/ro.svg"},capital:["Bucharest"],population:19286123,region:"Europe",subregion:"Southeast Europe",languages:{ron:"Romanian"},currencies:{RON:{name:"Romanian leu",symbol:"lei"}},timezones:["UTC+02:00"],borders:["BGR","HUN","MDA","SRB","UKR"],area:238397},
  {name:{common:"Russia"},cca3:"RUS",flags:{svg:"https://flagcdn.com/ru.svg"},capital:["Moscow"],population:144104080,region:"Europe",subregion:"Eastern Europe",languages:{rus:"Russian"},currencies:{RUB:{name:"Russian ruble",symbol:"₽"}},timezones:["UTC+02:00","UTC+03:00","UTC+04:00","UTC+05:00","UTC+06:00","UTC+07:00","UTC+08:00","UTC+09:00","UTC+10:00","UTC+11:00","UTC+12:00"],borders:["AZE","BLR","CHN","EST","FIN","GEO","KAZ","PRK","LVA","LTU","MNG","NOR","POL","UKR"],area:17098242},
  {name:{common:"Saudi Arabia"},cca3:"SAU",flags:{svg:"https://flagcdn.com/sa.svg"},capital:["Riyadh"],population:34813867,region:"Asia",subregion:"Western Asia",languages:{ara:"Arabic"},currencies:{SAR:{name:"Saudi riyal",symbol:"﷼"}},timezones:["UTC+03:00"],borders:["IRQ","JOR","KWT","OMN","QAT","UAE","YEM"],area:2149690},
  {name:{common:"Singapore"},cca3:"SGP",flags:{svg:"https://flagcdn.com/sg.svg"},capital:["Singapore"],population:5685807,region:"Asia",subregion:"South-Eastern Asia",languages:{eng:"English",msa:"Malay",tam:"Tamil",zho:"Chinese"},currencies:{SGD:{name:"Singapore dollar",symbol:"$"}},timezones:["UTC+08:00"],borders:[],area:710},
  {name:{common:"South Africa"},cca3:"ZAF",flags:{svg:"https://flagcdn.com/za.svg"},capital:["Pretoria"],population:59308690,region:"Africa",subregion:"Southern Africa",languages:{afr:"Afrikaans",eng:"English",zul:"Zulu"},currencies:{ZAR:{name:"South African rand",symbol:"R"}},timezones:["UTC+02:00"],borders:["BWA","LSO","MOZ","NAM","SWZ","ZWE"],area:1221037},
  {name:{common:"South Korea"},cca3:"KOR",flags:{svg:"https://flagcdn.com/kr.svg"},capital:["Seoul"],population:51780579,region:"Asia",subregion:"Eastern Asia",languages:{kor:"Korean"},currencies:{KRW:{name:"South Korean won",symbol:"₩"}},timezones:["UTC+09:00"],borders:["PRK"],area:100210},
  {name:{common:"Spain"},cca3:"ESP",flags:{svg:"https://flagcdn.com/es.svg"},capital:["Madrid"],population:47351567,region:"Europe",subregion:"Southern Europe",languages:{spa:"Spanish"},currencies:{EUR:{name:"Euro",symbol:"€"}},timezones:["UTC","UTC+01:00"],borders:["AND","FRA","GIB","PRT","MAR"],area:505992},
  {name:{common:"Sri Lanka"},cca3:"LKA",flags:{svg:"https://flagcdn.com/lk.svg"},capital:["Sri Jayawardenepura Kotte"],population:21919000,region:"Asia",subregion:"Southern Asia",languages:{sin:"Sinhala",tam:"Tamil"},currencies:{LKR:{name:"Sri Lankan rupee",symbol:"Rs"}},timezones:["UTC+05:30"],borders:[],area:65610},
  {name:{common:"Sweden"},cca3:"SWE",flags:{svg:"https://flagcdn.com/se.svg"},capital:["Stockholm"],population:10353442,region:"Europe",subregion:"Northern Europe",languages:{swe:"Swedish"},currencies:{SEK:{name:"Swedish krona",symbol:"kr"}},timezones:["UTC+01:00"],borders:["FIN","NOR"],area:450295},
  {name:{common:"Switzerland"},cca3:"CHE",flags:{svg:"https://flagcdn.com/ch.svg"},capital:["Bern"],population:8654622,region:"Europe",subregion:"Western Europe",languages:{deu:"German",fra:"French",ita:"Italian",roh:"Romansh"},currencies:{CHF:{name:"Swiss franc",symbol:"Fr"}},timezones:["UTC+01:00"],borders:["AUT","FRA","ITA","LIE","DEU"],area:41285},
  {name:{common:"Tanzania"},cca3:"TZA",flags:{svg:"https://flagcdn.com/tz.svg"},capital:["Dodoma"],population:59734213,region:"Africa",subregion:"Eastern Africa",languages:{eng:"English",swa:"Swahili"},currencies:{TZS:{name:"Tanzanian shilling",symbol:"Sh"}},timezones:["UTC+03:00"],borders:["BDI","COD","KEN","MWI","MOZ","RWA","UGA","ZMB"],area:945087},
  {name:{common:"Thailand"},cca3:"THA",flags:{svg:"https://flagcdn.com/th.svg"},capital:["Bangkok"],population:69799978,region:"Asia",subregion:"South-Eastern Asia",languages:{tha:"Thai"},currencies:{THB:{name:"Thai baht",symbol:"฿"}},timezones:["UTC+07:00"],borders:["MMR","KHM","LAO","MYS"],area:513120},
  {name:{common:"Turkey"},cca3:"TUR",flags:{svg:"https://flagcdn.com/tr.svg"},capital:["Ankara"],population:84339067,region:"Asia",subregion:"Western Asia",languages:{tur:"Turkish"},currencies:{TRY:{name:"Turkish lira",symbol:"₺"}},timezones:["UTC+03:00"],borders:["ARM","AZE","BGR","GEO","GRC","IRN","IRQ","SYR"],area:783562},
  {name:{common:"Uganda"},cca3:"UGA",flags:{svg:"https://flagcdn.com/ug.svg"},capital:["Kampala"],population:45741000,region:"Africa",subregion:"Eastern Africa",languages:{eng:"English",swa:"Swahili"},currencies:{UGX:{name:"Ugandan shilling",symbol:"Sh"}},timezones:["UTC+03:00"],borders:["COD","KEN","RWA","SSD","TZA"],area:241550},
  {name:{common:"Ukraine"},cca3:"UKR",flags:{svg:"https://flagcdn.com/ua.svg"},capital:["Kyiv"],population:44134693,region:"Europe",subregion:"Eastern Europe",languages:{ukr:"Ukrainian"},currencies:{UAH:{name:"Ukrainian hryvnia",symbol:"₴"}},timezones:["UTC+02:00"],borders:["BLR","HUN","MDA","POL","ROU","RUS","SVK"],area:603550},
  {name:{common:"United Arab Emirates"},cca3:"ARE",flags:{svg:"https://flagcdn.com/ae.svg"},capital:["Abu Dhabi"],population:9890400,region:"Asia",subregion:"Western Asia",languages:{ara:"Arabic"},currencies:{AED:{name:"United Arab Emirates dirham",symbol:"د.إ"}},timezones:["UTC+04:00"],borders:["OMN","SAU"],area:83600},
  {name:{common:"United Kingdom"},cca3:"GBR",flags:{svg:"https://flagcdn.com/gb.svg"},capital:["London"],population:67215293,region:"Europe",subregion:"Northern Europe",languages:{eng:"English"},currencies:{GBP:{name:"British pound",symbol:"£"}},timezones:["UTC-08:00","UTC-05:00","UTC-04:00","UTC-03:00","UTC-02:00","UTC","UTC+01:00","UTC+02:00","UTC+06:00"],borders:["IRL"],area:242900},
  {name:{common:"United States"},cca3:"USA",flags:{svg:"https://flagcdn.com/us.svg"},capital:["Washington, D.C."],population:329484123,region:"Americas",subregion:"North America",languages:{eng:"English"},currencies:{USD:{name:"United States dollar",symbol:"$"}},timezones:["UTC-12:00","UTC-11:00","UTC-10:00","UTC-09:00","UTC-08:00","UTC-07:00","UTC-06:00","UTC-05:00","UTC-04:00","UTC+10:00","UTC+12:00"],borders:["CAN","MEX"],area:9372610},
  {name:{common:"Uruguay"},cca3:"URY",flags:{svg:"https://flagcdn.com/uy.svg"},capital:["Montevideo"],population:3473727,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{UYU:{name:"Uruguayan peso",symbol:"$"}},timezones:["UTC-03:00"],borders:["ARG","BRA"],area:176215},
  {name:{common:"Venezuela"},cca3:"VEN",flags:{svg:"https://flagcdn.com/ve.svg"},capital:["Caracas"],population:28435943,region:"Americas",subregion:"South America",languages:{spa:"Spanish"},currencies:{VES:{name:"Venezuelan bolívar soberano",symbol:"Bs.S"}},timezones:["UTC-04:00"],borders:["BRA","COL","GUY"],area:916445},
  {name:{common:"Vietnam"},cca3:"VNM",flags:{svg:"https://flagcdn.com/vn.svg"},capital:["Hanoi"],population:97338583,region:"Asia",subregion:"South-Eastern Asia",languages:{vie:"Vietnamese"},currencies:{VND:{name:"Vietnamese đồng",symbol:"₫"}},timezones:["UTC+07:00"],borders:["CHN","KHM","LAO"],area:331212},
  {name:{common:"Zambia"},cca3:"ZMB",flags:{svg:"https://flagcdn.com/zm.svg"},capital:["Lusaka"],population:18383956,region:"Africa",subregion:"Eastern Africa",languages:{eng:"English"},currencies:{ZMW:{name:"Zambian kwacha",symbol:"ZK"}},timezones:["UTC+02:00"],borders:["AGO","BWA","COD","MWI","MOZ","NAM","TZA","ZWE"],area:752618},
  {name:{common:"Zimbabwe"},cca3:"ZWE",flags:{svg:"https://flagcdn.com/zw.svg"},capital:["Harare"],population:14862927,region:"Africa",subregion:"Eastern Africa",languages:{eng:"English",sna:"Shona",nde:"Ndebele"},currencies:{ZWL:{name:"Zimbabwean dollar",symbol:"$"}},timezones:["UTC+02:00"],borders:["BWA","MOZ","ZAF","ZMB"],area:390757},
]

export async function fetchAllCountries() {
  try {
    const res = await fetch('https://restcountries.com/v3.1/all')
    if (res.ok) {
      const data = await res.json()
      return data.sort((a, b) => a.name.common.localeCompare(b.name.common))
    }
  } catch {}
  return [...BUILTIN].sort((a, b) => a.name.common.localeCompare(b.name.common))
}

export async function fetchCountryByCode(code) {
  try {
    const res = await fetch(`https://restcountries.com/v3.1/alpha/${code}`)
    if (res.ok) {
      const data = await res.json()
      return Array.isArray(data) ? data[0] : data
    }
  } catch {}
  const found = BUILTIN.find(c => c.cca3 === code)
  if (found) return found
  throw new Error('Country not found')
}

export async function fetchCountriesByCodes(codes) {
  if (!codes?.length) return []
  try {
    const res = await fetch(`https://restcountries.com/v3.1/alpha?codes=${codes.join(',')}`)
    if (res.ok) return res.json()
  } catch {}
  return BUILTIN.filter(c => codes.includes(c.cca3))
}